# Используйте базовый образ Python
FROM python:3.11

# Установите переменную окружения для отключения вывода байт-кодов Python
ENV PYTHONDONTWRITEBYTECODE 1

# Установите переменную окружения для предотвращения буферизации вывода
ENV PYTHONUNBUFFERED 1

# Установите рабочую директорию в /app
WORKDIR /app

# Скопируйте зависимости проекта в текущую директорию
COPY requirements.txt /app/

# Установите зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Скопируйте текущий каталог в /app в контейнере
COPY . /app/

# Определите команду, которая будет запущена при старте контейнера
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
